# DB
DB_HOST = ''
DB_NAME = ''
DB_USER = ''
DB_PASS = ''

# Facebook
FACEBOOK_APP_KEY = ''
FACEBOOK_VERIFY_TOKEN = ''

# Twitter
TWITTER_CONSUMER_KEY = ''
TWITTER_CONSUMER_SECRET = ''
TWITTER_ACCESS_TOKEN = ''
TWITTER_ACCESS_TOKEN_SECRET = ''