CREATE DATABASE IF NOT EXISTS `maju_bot` DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `maju_bot`.`weather` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `temperature` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `humidity` DECIMAL(5,2) NOT NULL DEFAULT 0,
  `rain` VARCHAR(45) NOT NULL DEFAULT 0,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB